multimedia/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('images/', views.image_list, name='image_list'),
    path('videos/', views.video_list, name='video_list'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('upload_video/', views.upload_video, name='upload_video'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

multimedia_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('multimedia.urls')),
]

multimedia/models.py
import os
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Image(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(default=os.path.join("assets", "image.png"), upload_to="images")
    description = models.TextField()

    def __str__(self):
        return f"{self.title}"

def validate_video_fields(value_dict):
    video_file = value_dict.get('video')
    video_link = value_dict.get('video_link')

    if not video_file and not video_link:
        raise ValidationError("Please provide either a video file or a video link, or both.")

class Video(models.Model):
    title = models.CharField(max_length=100)
    video = models.FileField(upload_to="videos", blank=True, null=True)
    video_link = models.CharField(max_length=150, blank=True, null=True)
    description = models.TextField()

    def clean(self):
        validate_video_fields({'video': self.video, 'video_link': self.video_link})

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.title}"

multimedia/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Image, Video

# Create your views here.

def home(request):
    images = Image.objects.order_by('-id')[:4]
    videos = Video.objects.order_by('-id')[:4]
    
    return render(request, 'index.html', {'images':images, 'videos': videos})

def image_list(request):
    images = Image.objects.all()
    return render(request, 'pages/image_list.html', {'images': images})

def video_list(request):
    videos = Video.objects.all()
    return render(request, 'pages/video_list.html', {'videos': videos})

def upload_image(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        image = request.FILES.get('image')
        description = request.POST.get('description')
        Image.objects.create(title=title, image=image, description=description)
        messages.success(request, 'Video has been uploaded successfully')
        
        return redirect('image_list')
    return render(request, 'upload/upload_image.html')

def upload_video(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        video = request.FILES.get('video')
        video_link = request.POST.get('video_link')
        description = request.POST.get('description')

        if not video and not video_link:
            # Handle the case where neither video nor video_link is provided
            messages.error(request, 'Please provide either a video file or a video link.')
            return render(request, 'upload/upload_video.html')

        # Create the Video instance based on the provided input
        if video:
            Video.objects.create(title=title, video=video, description=description)
            messages.success(request, 'Video has been uploaded successfully')
        else:
            Video.objects.create(title=title, video_link=video_link, description=description)
            messages.success(request, 'Video has been uploaded successfully')

        return redirect('video_list')

    return render(request, 'upload/upload_video.html')

multimedia/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <title>CINEWAP</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Coming+Soon&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300&display=swap');
      
      body {
        font-family: 'Open Sans', sans-serif;
        margin: 0;
        background: fixed #ddd;
      }
      
      nav {
        background-color: #45a049;
        color: white;
        padding: 10px 0;
        position: fixed;
        width: 100%;
        top: 0;
        z-index: 1;
      }
      
      .nav {
        max-width: 1200px;
        margin: 0 auto;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
      
      .logo a {
        color: #ffcc00;
        text-decoration: none;
        font-size: 24px;
        font-weight: bold;
      }
      
      ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        display: flex;
      }
      
      ul li {
        margin-right: 20px;
      }
      
      ul li a {
        color: white;
        text-decoration: none;
        font-size: 18px;
      }
      
      ul li div {
        font-size: 18px;
      }
      
      ul li a:hover {
        border-bottom: 2px solid #ffcc00;
        padding-bottom: 5px;
        transition: border-bottom 0.1s ease;
      }
      
      .dropdown {
        position: relative;
      }
      
      .dropdown-content {
        display: none;
        position: absolute;
        background-color: #333;
        min-width: 160px;
        box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.2);
        z-index: 1;
      }
      
      .dropdown-content a {
        color: white;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        text-align: left;
      }
      
      .dropdown-content a:hover {
        background-color: #555;
      }
      
      .dropdown:hover .dropdown-content {
        display: block;
      }
      
      /* Responsive Navigation Menu */
      .menu-icon {
        display: none;
        cursor: pointer;
        font-size: 24px;
        color: white;
      }
      
      .header {
        text-align: center;
      }
      
      .banner {
        height: 300px;
        background: url('../../../media/assets/image.png') no-repeat center/cover;
        color: white;
        text-align: center;
        padding: 50px;
        position: relative;
      }
      
      .banner h1 {
        margin-top: 50px;
        font-size: 2em;
      }
      
      .banner p {
        font-size: 1.2em;
      }
      
      .banner2 {
        margin-top: 40px;
        width: 100%;
        height: 400px;
        object-fit: cover;
        position: relative;
      }
      
      .banner3 {
        height: 300px;
        background: url('../../../media/assets/image.png') no-repeat center center/cover;
        color: white;
        text-align: center;
        padding: 50px;
        margin-top: 30px;
      }
      
      .banner3 h1 {
        font-size: 5em;
        font-family: 'Coming Soon', cursive;
        margin-top: 20px;
        color: #ffcc00;
      }
      
      /* card styling */
      .card-body {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-evenly;
      }
      
      .card {
        width: calc(33.33% - 20px);
        margin: 10px;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 5px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        background-color: #fff;
        transition: box-shadow 0.3s ease;
      }
      
      .card:hover {
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.4);
      }
      
      .card img {
        width: 100%;
        height: 200px;
        object-fit: cover;
        border-radius: 5px;
        margin-bottom: 10px;
      }
      
      .card video {
        width: 100%;
        border-radius: 8px;
        margin-bottom: 10px;
      }
      
      .card iframe {
        width: 100%;
        border-radius: 5px;
        margin-bottom: 10px;
      }
      
      .card h3 {
        font-size: 18px;
        margin-bottom: 10px;
      }
      
      .card p {
        font-size: 14px;
        color: #666;
        margin-bottom: 10px;
      }
      
      /* Form styling */
      form {
        max-width: 400px;
        margin: 20px auto;
        padding: 20px;
        border: 1px solid #ddd;
        border-radius: 5px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        background-color: #fff;
      }
      
      label {
        display: block;
        margin-bottom: 8px;
        font-weight: bold;
      }
      
      input[type='text'],
      input[type='file'],
      input[type='url'],
      textarea,
      select {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        box-sizing: border-box;
        border: 1px solid #ddd;
        border-radius: 5px;
      }
      
      button {
        background-color: #4caf50;
        color: white;
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
      }
      
      button:hover {
        background-color: #45a049;
      }
      
      @media only screen and (max-width: 600px) {
        .nav {
          display: flex;
          flex-direction: column;
          align-items: flex-start;
          padding: 0 20px;
          justify-content: space-between;
        }
      
        .logo a {
          margin-bottom: 10px;
        }
      
        ul {
          flex-direction: column;
          align-items: flex-start;
        }
      
        ul li {
          margin-right: 0;
          margin-bottom: 10px;
        }
      
        .menu-icon {
          display: flex;
          float: right;
        }
      
        ul {
          display: none;
        }
      
        ul.show {
          display: flex;
        }
      
        .banner {
          margin-top: 60px;
          padding: 20px;
        }
      
        .header h1 {
          margin-top: 80px;
          font-size: 24px;
        }
      }
      
      /* Tablet Styling */
      @media only screen and (min-width: 601px) and (max-width: 900px) {
        .nav {
          padding: 10px 20px;
        }
      
        ul li {
          margin-right: 10px;
          margin-bottom: 0;
        }
      
        .logo a {
          margin-bottom: 0;
        }
      
        .card {
          width: 40%;
        }
      
        .banner {
          margin-top: 60px;
        }
      
        .header {
          margin-top: 80px;
          font-size: 28px;
        }
      
        .banner2 {
          height: 250px;
        }
      }
      
      /* Desktop Styling */
      @media only screen and (min-width: 901px) {
        .card {
          width: 20%;
        }
      
        .nav {
          padding: 10px 40px;
        }
      
        ul {
          flex-direction: row;
          align-items: center;
        }
      
        ul li {
          margin-right: 20px;
          margin-bottom: 0;
        }
      
        .header {
          margin-top: 80px;
          font-size: 32px;
        }
      
        .banner {
          margin-top: 50px;
        }
      
        .banner2 {
          height: 350px;
        }
      }
      
      /* Mobile Styling */
      @media (max-width: 600px) {
        nav {
          padding: 10px 0;
        }
      
        .nav {
          flex-direction: column;
          align-items: flex-start;
        }
      
        .logo a {
          margin-bottom: 10px;
        }
      
        ul {
          flex-direction: column;
          align-items: flex-start;
        }
      
        .banner {
          margin-top: 60px;
          height: 200px;
          padding: 20px;
        }
      
        .banner2 {
          height: 200px;
        }
      
        .banner3 {
          height: 200px;
          padding: 20px;
        }
      
        .banner3 h1 {
          font-size: 24px;
          margin-top: 10px;
        }
      
        .card {
          width: 100%;
        }
      
        form {
          max-width: 80%;
        }
      
        .header {
          margin-top: 80px;
          font-size: 32px;
        }
      }
      
      /* Footer styling */
      footer {
        background-color: #333;
        color: white;
        padding: 20px 0;
        width: 100%;
      }
      
      .footer-container {
        max-width: 1200px;
        margin: 0 auto;
        padding: 0 20px;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
      
      .footer-logo a {
        color: #ffcc00;
        text-decoration: none;
        font-size: 18px;
        font-weight: bold;
      }
      
      .footer-links ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        display: flex;
        margin-bottom: 0;
      }
      
      .footer-links li {
        margin-right: 20px;
      }
      
      .footer-links a {
        color: white;
        text-decoration: none;
        font-size: 16px;
      }
      
      .footer-bottom {
        text-align: center;
        margin-top: 10px;
      }
      
      .footer-bottom p {
        font-size: 14px;
      }
    </style>
  </head>
  <body>
    <nav>
      <div class="nav">
        <div class="logo">
          <a href="/">CINEWAP</a>
        </div>
        <div class="menu-icon" onclick="toggleMenu()">☰</div>
        <div>
          <ul id="menu" class="menu">
            <li>
              <a href="/">HOME</a>
            </li>
            <li>
              <a href="{% url 'image_list' %}">IMAGES</a>
            </li>
            <li>
              <a href="{% url 'video_list' %}">VIDEOS</a>
            </li>
            <li class="dropdown">
              <div class="dropbtn">
                UPLOAD<div class="dropdown-content">
                  <a href="{% url 'upload_image' %}">UPLOAD IMAGE</a>
                  <a href="{% url 'upload_video' %}">UPLOAD VIDEO</a>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}

    {% endblock %}
    <!-- Footer -->
    <footer>
      <div class="footer-container">
        <div class="footer-logo">
          <a href="/">CINEWAP</a>
        </div>
        <div class="footer-links">
          <ul>
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="{% url 'image_list' %}">Images</a>
            </li>
            <li>
              <a href="{% url 'video_list' %}">Videos</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="footer-bottom">
        <p>&copy; 2023 CINEWAP. All rights reserved.</p>
      </div>
    </footer>
    <script>
      function toggleMenu() {
        const menu = document.getElementById('menu')
        menu.classList.toggle('show')
      }
    </script>
  </body>
</html>

multimedia/templates/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="banner">
    <h1>Welcome to Multimedia World</h1>
    <p>Explore a variety of images and videos!</p>
  </div>
  <h1 class="header">RECENT IMAGES</h1>
  <div class="card-body">
    {% for image in images %}
      <div class="card">
        <img src="{{ image.image.url }}/" alt="{{ image.title }}" />
        <h3>{{ image.title }}</h3>
        <p>{{ image.description|truncatechars:100 }}</p>
      </div>
    {% endfor %}
  </div>
  <iframe width="100% " height="500" src="https://www.youtube.com/embed/3GeVsXHN1Ks?si=VrlrnoavCb6G-7ne" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  <h1 class="header">RECENT VIDEOS</h1>
  <div class="card-body">
    {% for video in videos %}
      <div class="card">
        {% if video.video %}
          <!-- Display video file if available -->
          <video loop autoplay muted controls>
            <source src="{{ video.video.url }}" type="video/mp4" />
          </video>
        {% elif video.video_link %}
          <!-- Display video link if available -->
          <!--<iframe width="100%" height="315" src="{{ video.video_link }}" frameborder="0" allowfullscreen></iframe>-->
          <iframe width="100%" height="" src="{{ video.video_link }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        {% endif %}
        <h3>{{ video.title }}</h3>
        <p>{{ video.description|truncatechars:100 }}</p>
      </div>
    {% endfor %}
  </div>
  <div class="banner3">
    <h1>REGISTRATION COMING SOON!!!!!</h1>
  </div>
{% endblock %}

multimedia/templates/pages/image_list.html
{% extends 'base.html' %}
{% block content %}
  <style>
    .card {
      border: 1px solid #ddd;
      margin: 10px;
      padding: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
      position: relative;
    }
    
    .modal {
      display: none;
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      max-width: 100%;
      max-height: 80%;
      overflow: auto;
      padding: 20px;
      background-color: #fff;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
      z-index: 1000;
      text-align: center;
    }
    
    .modal-backdrop {
      display: none;
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.5);
      z-index: 900;
    }
    
    .details-button {
      position: absolute;
      bottom: 10px;
      left: 50%;
      transform: translateX(-50%);
      background-color: #4caf50;
      color: #fff;
      padding: 8px 16px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    
    .details-button:hover {
      background-color: #45a049;
    }
    
    img {
      width: 100%;
      height: auto;
      border-radius: 8px;
      margin-bottom: 10px;
    }
    
    #modalTitle {
      font-size: 24px;
      margin-bottom: 10px;
    }
    
    #modalImage {
      max-height: 50vh;
      border-radius: 8px;
      margin-bottom: 10px;
    }
    
    #modalDescription {
      font-size: 16px;
      margin-bottom: 20px;
    }
    
    #modalCloseButton {
      background-color: #f44336;
      color: #fff;
      padding: 8px 16px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    
    #modalCloseButton:hover {
      background-color: #d32f2f;
    }
  </style>

  <h1 class="header">IMAGES</h1>
  <div class="card-body">
    {% for image in images %}
      <div class="card">
        <img src="{{ image.image.url }}" alt="{{ image.title }}" />
        <h3>{{ image.title }}</h3>
        <p>{{ image.description|truncatechars:50 }}</p>
        <button class="details-button" onclick="openImageModal('{{ image.id }}', '{{ image.image.url }}', '{{ image.title }}', '{{ image.description }}')">Details</button>
      </div>
    {% endfor %}

    <!-- Modal -->
    <div class="modal-backdrop" onclick="closeImageModal()"></div>
    <div class="modal" id="imageModal">
      <h2 id="modalTitle"></h2>
      <img id="modalImage" />
      <p id="modalDescription"></p>
      <button id="modalCloseButton" onclick="closeImageModal()">Close</button>
    </div>
  </div>

  <script>
    function openImageModal(id, imageUrl, title, description) {
      document.getElementById('modalTitle').innerText = title
      document.getElementById('modalImage').src = imageUrl
      document.getElementById('modalDescription').innerText = description
    
      document.querySelector('.modal-backdrop').style.display = 'block'
      document.getElementById('imageModal').style.display = 'block'
    }
    
    function closeImageModal() {
      document.querySelector('.modal-backdrop').style.display = 'none'
      document.getElementById('imageModal').style.display = 'none'
    }
  </script>
{% endblock %}

multimedia/templates/pages/video_list.html
{% extends 'base.html' %}
{% block content %}
  <style>
    footer {
      width: 100%;
      position: fixed;
      bottom: 0;
    }
    
    .card {
      border: 1px solid #ddd;
      margin: 10px;
      padding: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
      position: relative;
    }
    
    .modal {
      display: none;
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      padding: 20px;
      background-color: #fff;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border-radius: 8px;
      z-index: 1000;
    }
    
    .modal-backdrop {
      display: none;
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.5); /* Semi-transparent black overlay */
      z-index: 900;
    }
    
    .details-button {
      position: absolute;
      bottom: 10px;
      left: 50%;
      transform: translateX(-50%);
      background-color: #4caf50;
      color: #fff;
      padding: 8px 16px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
    
    .details-button:hover {
      background-color: #45a049;
    }
    
    video,
    iframe {
      width: 100%;
      height: 200px; /* Adjust the height as needed */
      border-radius: 8px;
      margin-bottom: 10px;
    }
  </style>

  <h1 class="header">VIDEOS</h1>
  <div class="card-body">
    {% for video in videos %}
      <div class="card">
        {% if video.video %}
          <video loop muted controls>
            <source src="{{ video.video.url }}" type="video/mp4" />
          </video>
        {% elif video.video_link %}
          <iframe width="100%" height="200px" src="{{ video.video_link }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        {% endif %}
        <button class="details-button" onclick="openModal('{{ video.id }}')">Details</button>
        <!-- modal -->
        <div class="modal" id="modal-{{ video.id }}">
          <h3>{{ video.title }}</h3>
          {% if video.video %}
            <video loop autoplay muted controls>
              <source src="{{ video.video.url }}" type="video/mp4" />
            </video>
          {% elif video.video_link %}
            <iframe width="100%" height="400px" src="{{ video.video_link }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
          {% endif %}
          <p>{{ video.description }}</p>
          <button onclick="closeModal('{{ video.id }}')">Close</button>
        </div>

        <!-- Modal Backdrop -->
        <div class="modal-backdrop" onclick="closeModal('{{ video.id }}')"></div>
      </div>
    {% endfor %}
  </div>

  <script>
    function openModal(videoId) {
      document.getElementById('modal-' + videoId).style.display = 'block'
      document.querySelector('.modal-backdrop').style.display = 'block'
    }
    
    function closeModal(videoId) {
      document.getElementById('modal-' + videoId).style.display = 'none'
      document.querySelector('.modal-backdrop').style.display = 'none'
    }
  </script>
{% endblock %}

multimedia/templates/upload/upload_image.html
{% extends 'base.html' %}
{% block content %}
  <style>
    footer {
      width: 100%;
      position: fixed;
      bottom: 0;
    }
    
    .messages {
      list-style: none;
      padding: 10px;
      margin: 0;
      background-color: #dff0d8;
      border: 1px solid #3c763d;
      color: #3c763d;
      border-radius: 4px;
    }
    
    .messages li {
      margin-bottom: 5px;
    }
    
    .messages.error {
      background-color: #f2dede;
      border: 1px solid #a94442;
      color: #a94442;
    }
    
    .message-success {
      color: #4caf50; /* Green color for success messages */
      background-color: #e7f6e7; /* Light green background */
      border: 1px solid #2d6e2d; /* Dark green border */
      padding: 10px;
      margin-bottom: 10px;
      border-radius: 5px;
    }
  </style>

  <h1 class="header">UPLOAD AN IMAGE</h1>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        {% if message.tags == 'message-error' %}
          <li class="message-error">{{ message }}</li>
        {% elif message.tags == 'message-success' %}
          <li class="message-success">{{ message }}</li>
        {% endif %}
      {% endfor %}
    </ul>
  {% endif %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_title">Title:</label>
    <input type="text" name="title" id="id_title" required />
    <br />
    <label for="id_image">Image:</label>
    <input type="file" name="image" id="id_image" accept="image/*" required />
    <br />
    <label for="id_title">Description:</label>
    <input type="text" name="description" id="id_title" required />
    <br />
    <button type="submit">Upload Image</button>
  </form>
{% endblock %}

multimedia/templates/upload/upload_video.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <style>
    .messages {
      list-style: none;
      padding: 10px;
      margin: 0;
      border-radius: 4px;
    }
    
    .messages li {
      margin-bottom: 5px;
    }
    
    .messages-error {
      background-color: #f2dede;
      border: 1px solid #a94442;
      color: #a94442;
    }
    
    .message-success {
      color: #4caf50; /* Green color for success messages */
      background-color: #e7f6e7; /* Light green background */
      border: 1px solid #2d6e2d; /* Dark green border */
      padding: 10px;
      margin-bottom: 10px;
      border-radius: 5px;
    }
  </style>
  <h1 class="header">UPLOAD A VIDEO</h1>

  <form method="post" enctype="multipart/form-data">
    <ul class="messages">
      {% for message in messages %}
        {% if message.tags == 'error' %}
          <li class="message-error">{{ message }}</li>
        {% elif message.tags == 'success' %}
          <li class="message-success">{{ message }}</li>
        {% endif %}
      {% endfor %}
    </ul>

    {% csrf_token %}
    <label for="id_title">Title:</label>
    <input type="text" name="title" id="id_title" required />
    <br />
    <label for="upload_type">Upload Type:</label>
    <select id="upload_type" name="upload_type" required>
      <option value="file" selected>Upload from device</option>
      <option value="link">Provide a video link</option>
    </select>
    <br />
    <div id="file_upload">
      <label for="id_video">Video:</label>
      <input type="file" name="video" id="id_video" accept="video/*" />
    </div>
    <div id="link_input" style="display: none;">
      <label for="id_video_link">Embed Video Link:</label>
      <input type="url" name="video_link" id="id_video_link" />
    </div>
    <br />
    <label for="id_description">Description:</label>
    <input type="text" name="description" id="id_description" required />
    <br />
    <button type="submit">Upload Video</button>
  </form>

  <script>
    document.getElementById('upload_type').addEventListener('change', function () {
      var fileUpload = document.getElementById('file_upload')
      var linkInput = document.getElementById('link_input')
      var videoLinkId = document.getElementById('id_video_link')
      var videoId = document.getElementById('id_video')
    
      if (this.value === 'file') {
        fileUpload.style.display = 'block'
        linkInput.style.display = 'none'
        videoLinkId.value = ''
      } else {
        fileUpload.style.display = 'none'
        linkInput.style.display = 'block'
        videoLinkId.value = ''
      }
    })
  </script>
{% endblock %}